### ISSUE TITLE
When checking for changes, X-Plane crashes

### ISSUE THREAD

**Issue by sanderdatema** [markcellis/X-KeyPad#88]
I'm not sure yet how to reproduce this and there is nothing in `Log.txt`. The odd thing is that the first time in a session I checked the box, did some tests, unchecked it and checked it again to start a new search. Then it crashed. So that seems to rule out datarefs that weren't available yet. X-Plane was running for about half an hour already.

Is there a wat to add some kind of debug log I can send you?

This was X-Plane 12.1

**Comment by markcellis** [comment]
Can you reliably reproduce the crash?Sent from my iPhoneOn May 24, 2024, at 06:49, Sander Datema ***@***.***> wrote:﻿
I'm not sure yet how to reproduce this and there is nothing in Log.txt. The odd thing is that the first time in a session I checked the box, did some tests, unchecked it and checked it again to start a new search. Then it crashed. So that seems to rule out datarefs that weren't available yet. X-Plane was running for about half an hour already.
Is there a wat to add some kind of debug log I can send you?

**Comment by sanderdatema** [comment]
Reliable as in that it happens a lot now. First round goes ok, second time is a crash.

**Comment by markcellis** [comment]
Is it with just the Zibo? Did you have anything in the filters?

**Comment by sanderdatema** [comment]
Yes, just the Zibo. The exact setting was 'last 10 seconds' and nothing else.

I just installed the latest beta of X-Plane. So far no crashes, maybe the problem was in the betas.

**Comment by markcellis** [comment]
Per our discussion it seems this might have been caused by an X-Plane update and is no longer an issue
